// <auto-generated />
namespace Toastmaster.Web.Console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Beta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Beta));
        
        string IMigrationMetadata.Id
        {
            get { return "201705251539352_Beta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
